# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60aeebb33e88928cd0d48ca43d574fdbbbb6662406799acf9269bb53a37b294c0062471f056e630fec7cbddb2814a5297f0c4ae626b3f0b1a7c95b5a660ca03a

test:
  secret_key_base: f8a65f60d00df2a2d2ce18ce262b9234f255e2ba9deca5d3de36e5232e5608b19d7d39c3c0d42b5b6abf9c9ac27bb6366fa3761b63abbbd4fc69a321e81d6b50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
